"""Create Project table

Revision ID: 8c002415272f
Revises:
Create Date: 2025-03-25 13:56:30.360480

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.mutable import MutableList
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = "8c002415272f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer, index=True, primary_key=True),
        sa.Column("title", sa.String, nullable=False),
        sa.Column("created_at", sa.DateTime, default=datetime.utcnow()),
        sa.Column("meeting_days", sa.String, default="Monday"),
        sa.Column("participants_id", MutableList.as_mutable(sa.JSON)),
        sa.Column("user_id", sa.Integer, nullable=False),
    )
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
